### ISSUE TITLE
settings for logs & live run

### ISSUE THREAD

**Issue by micboat** [Ph3nol/FT-Trading-Bot#1]
Hi @Ph3nol ,

Thanks for providing this tool. I have 2 questions:

1. Dry run is great. Can you provide some guidance on how to setup live runs. Changing ft_dry_run to "false" & setting it in the base config file doesn't work for me.  Am I missing something else?

2. Also, is it possible to add a feature to view logs via terminal using ./b i <name>  logs -f?

Thanks!

**Comment by Ph3nol** [comment]
Hey!


First, thank you for your interest.

I admit documentation is a little bit ~poor~ missing! 😅 Originally, this is my personal tool for using Freqtrade instances that I open sourced for sharing. Some missing points have to be added.

1. Can you double check about having `FT_DRY_RUN="true"` in your instance `./instances/*.sh` file? As you can see [here](https://github.com/Ph3nol/FT-Trading-Bot/blob/c488ed61ab97497bc1fc1dca161450adc6228f7a/b#L91), it is the final way to determine Freqtrade running mode.

2. For sure! I have [just pushed](https://github.com/Ph3nol/FT-Trading-Bot/commit/5f680a21fabf2e64983d771885e0c8b06a48abbf) it. 🤙

Have a good day!

**Comment by micboat** [comment]
Awesome, thanks a lot Ph3nol. 

The issue with the live run was actually an api problem on my end, not your code. The logs helped me identify that issue. I fixed that and its working perfectly with FT_DRY_RUN="false".

Thanks a lot for the logs enhancement.  🤙

Have a great day too!
